deltaDAO/portal-euprogigant

content/pages/index/featured.json

- replace "lorem ipsum" in the featured asset section

Enhancement: update featured section text

---

content/pages/index/featured.json
src/components/templates/Search/Filters.module.css

Fixes #12 
- filter buttons color is now correctly removed after deselection
- fix "Go to Data Sets" text on the main page button

Enhancement: interface issues

---

src/providers/Web3.tsx

- add WalletConnect option as web3 provider

Feat: add WalletConnect option as web3 provider

---

src/components/templates/Search/Filters.tsx

hotfix(search): select filter

---

content/pages/index/featured.json
src/components/templates/Search/utils.ts

- default sort by creation date in search page

feat: default sort by creation date in search page

---

apollo.config.js
codegen.yml
src/utils/ocean.ts

fix: update subgraph url

---

src/components/organisms/AssetContent/index.tsx

fix: asset details not showing for publisher

---

content/gdpr.example.json
content/gdpr.json
content/gdpr_.json
src/components/organisms/Footer.module.css
src/components/organisms/Footer.tsx
src/components/organisms/PrivacyPreferenceCenter.module.css
src/components/organisms/PrivacyPreferenceCenter.tsx

Fixes #https://github.com/deltaDAO/multi-repo-issues/issues/2
- update footer links (privacy, imprint, cookies) to redirect to the mvg portal

feat: update privacy policies

---

address.config.js

Adds missing account to whitelist

fix: add account

---

src/components/atoms/Input/InputElement.tsx
src/components/atoms/Input/index.tsx
src/components/molecules/FormFields/BoxSelection.tsx
src/components/molecules/FormFields/FilesInput/index.tsx
src/components/molecules/FormFields/ServiceSelfDescription.tsx
src/components/organisms/AssetActions/Edit/FormEditMetadata.tsx
src/components/pages/Publish/FormActions.tsx
src/components/pages/Publish/FormAlgoPublish.tsx
src/components/pages/Publish/FormPublish.tsx

- disable publish button if SD verification is in progress
- remove defaultChecked prop from BoxSelection component

enhancement: disable publish button if SD verification is in progress

---

src/components/atoms/Publisher/index.tsx
src/components/molecules/WalletNetworkSwitcher.tsx
src/components/molecules/Web3Feedback.tsx

- fix wallet network switcher target network
- remove 3box profile broken integration

fix: network switcher

---

content/site.json
src/components/organisms/Footer.tsx
src/components/organisms/PoweredBy.tsx

enhancement: update footer content

---

content/site.json
src/components/molecules/Menu.tsx
src/components/molecules/UserPreferences/Onboarding.tsx
src/components/molecules/Wallet/Details.module.css
src/components/molecules/Wallet/Details.tsx
src/components/molecules/Wallet/index.tsx
src/components/pages/Home.tsx
src/components/pages/Profile/Header/index.tsx
src/components/pages/Profile/History/PublishedList.module.css
src/components/pages/Profile/History/PublishedList.tsx
src/components/templates/Search/Filters.module.css
src/components/templates/Search/Filters.tsx
src/components/templates/Search/index.module.css
src/components/templates/Search/index.tsx
src/models/SortAndFilters.ts
src/providers/UserPreferences.tsx
src/utils/aquarius.ts
tests/unit/__fixtures__/useUserPreferences.ts

- add catalogue link to menubar
- move profile and bookmarks links to wallet dropdown
- update search page filter logic
- add onboarding show/hide toggle

feat: update menubar + onboarding module

---

src/providers/UserPreferences.tsx

- remove showOnboarding preference from localstorage
- default showOnboarding value to false

enhancement: default show onboarding to false

---

src/components/Footer/Links.tsx

feat: update imprint link

---

src/components/Publish/_utils.ts

@moritzkirstein @LucaMilanese90 
Fixes #
- compliance version to main for Open House Day

Change compliance version from v1 to main

---

app.config.js
chains.config.js
networksMetadata.config.js
scripts/write-networks-metadata.js
src/@hooks/useNetworkMetadata/utils.ts
src/@utils/ocean/index.ts
src/@utils/onboarding.ts
src/@utils/wallet/chains.ts
src/@utils/wallet/index.ts
src/components/@shared/AddToken/index.module.css
src/components/@shared/AddToken/index.tsx
src/components/@shared/Onboarding/Steps/ImportCustomTokens.tsx
src/components/@shared/Onboarding/index.tsx
src/components/Header/Wallet/Details.tsx

See https://github.com/deltaDAO/mvg-portal/pull/503

Feat: Oasis Pontus-x Support (#503)

---

src/components/Asset/AssetActions/Download/ContractingProvider/index.tsx

- Adds support for AutomationWallet for Contracting Provider checks

feat: add automation wallet to contracting provider component

---

content/site.json

Remove CIX

---

content/site.json

Update Ecosystem Links

---

content/site.json

Update Ecosystem Link

---

src/stylesGlobal/_variables.css

Fixes #
- added menu-caret-activ-fill-color

fix: add menu-caret-activ-fill-color

---

src/components/Asset/AssetActions/Download/index.tsx

Fixes #
- go to service button

fix: go to service Button

---

app.config.js
src/components/Header/UserPreferences/Automation/Details.tsx
src/components/Header/UserPreferences/Automation/index.tsx

Fixes #
- add optional chaining to balance properties
- update default terms and conditions url

fix: add optional chaning for balance properties and update default terms and conditions url 
